version: 0.2
phases:
  install:
    commands:
      - echo 'hello world'

  build:
    commands:
      - echo 'helloworld'
  
artifacts:
  files:
    - 'arn:aws:s3:::pipeline21'
  base-directory: 'output'
  discard-paths: yes
